# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtv', '0003_remove_order_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
