# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtv', '0004_auto_20170529_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
